
[server]
httpAddress = ":8000"
rpcAddress = ":8001"
webClient = "/groups/flyem/proj/cluster/miniconda/envs/flyem/diced/diced/dvid-console/dist-lite.html"
instance_id_gen = "sequential"
instance_id_start = 100  # new ids start at least from this.

note = """
{"source": "gs://flyem-alignment-quick-eval"}
"""

[logging]
logfile = "/groups/flyem/data/scratchspace/ingestion-configs/scripts/logs/flyem-alignment-quick-eval.log"
max_log_size = 500 # MB
max_log_age = 30   # days
[store]
    [store.mutable]
        engine = "gbucket"
        bucket= "flyem-alignment-quick-eval"
